doc-warnings: true
test-warnings: false
strictness: low
max-line-length: 79
uses:
    - kombu
    - amqp
autodetect: true
requirements:
    - requirements/default.txt
    - requirements/test.txt
ignore-paths:
    - docs
    - t
python-targets:
    - 2
    - 3
