doc-warnings: false
test-warnings: false
max-line-length: 79
uses:
    - kombu
    - amqp
autodetect: true
requirements:
    - requirements/default.txt
    - requirements/test.txt
ignore-paths:
    - docs
    - t
python-targets:
    - 2
    - 3
pep8:
    full: true
    disable:
        - N806
        - N802
        - N801
        - N803
pyroma:
    run: true
pylint:
    disable:
        - missing-docstring
        - too-many-arguments
        - too-many-locals
        - redefined-builtin
