doc-warnings: false
test-warnings: false
max-line-length: 79
inherits:
    - strictness_veryhigh
uses:
    - celery
autodetect: true
requirements:
    - requirements/default.txt
    - requirements/test.txt
ignore-paths:
    - docs
    - t
python-targets:
    - 2
    - 3
pep8:
    full: true
    disable:
        - N806
        - N802
        - N801
        - N803
pyroma:
    run: true
pylint:
    disable:
        - missing-docstring
        - too-many-arguments
        - too-many-locals
        - redefined-builtin
        - not-callable
        - cyclic-import
        - expression-not-assigned
        - lost-exception
        - dangerous-default-value
        - unused-argument
        - protected-access
    options:
        exclude-protected: _reader, _writer, _popen, _sentinel_poll, _job, _is_alive, _write_to, _scheduled_for, _terminated, _accepted, _set_terminated, _payload, _cancel
