language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python: 2.7
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=2.7
    - TOXENV=3.3
    - TOXENV=3.4
    - TOXENV=pypy
install:
  - pip install tox
script:
  - tox -v -- -v
after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coveralls
notifications:
  irc:
    channels:
      - "chat.freenode.net#celery"
    on_success: change
    on_failure: change
