[tox]
envlist = py25,py26,py27,pypy

[testenv]
distribute = True
sitepackages = False
commands = nosetests

[testenv:py32]
recreate = True
basepython = python3.2
changedir = .tox
deps = -r{toxinidir}/requirements/default.txt
       -r{toxinidir}/requirements/test-py3k.txt
commands = {toxinidir}/contrib/release/removepyc.sh {toxinidir}
           nosetests -vd celery.tests                           \
                --with-coverage3                                \
                --cover3-branch                                 \
                --cover3-xml                                    \
                --cover3-xml-file={toxinidir}/coverage.xml      \
                --cover3-html                                   \
                --cover3-html-dir={toxinidir}/cover             \
                --cover3-package=celery                         \
                --cover3-exclude="celery celery.tests.*         \
                        celery.bin.celeryd_multi                \
                        celery.bin.celeryd_detach               \
                        celery.bin.celeryctl                    \
                        celery.bin.camqadm                      \
                        celery.execute                          \
                        celery.local                            \
                        celery.platforms                        \
                        celery.utils.patch                      \
                        celery.utils.compat                     \
                        celery.utils.mail                       \
                        celery.utils.functional                 \
                        celery.utils.dispatch*                  \
                        celery.utils.term                       \
                        celery.db.a805d4bd                      \
                        celery.db.dfd042c7                      \
                        celery.contrib*                         \
                        celery.concurrency.threads              \
                        celery.concurrency.processes.pool       \
                        celery.concurrency.gevent               \
                        celery.backends.mongodb                 \
                        celery.backends.tyrant                  \
                        celery.backends.cassandra               \
                        celery.events.dumper                    \
                        celery.events.cursesmon"                \
                --with-xunit                                    \
                --xunit-file={toxinidir}/nosetests.xml

[testenv:py27]
basepython = python2.7
deps = -r{toxinidir}/requirements/default.txt
       -r{toxinidir}/requirements/test.txt
commands = {toxinidir}/contrib/release/removepyc.sh {toxinidir}
           nosetests --with-xunit                               \
                     --xunit-file={toxinidir}/nosetests.xml     \
                     --with-coverage3 --cover3-xml              \
                     --cover3-html-dir={toxinidir}/cover        \
                     --cover3-xml-file={toxinidir}/coverage.xml

[testenv:py26]
basepython = python2.6
deps = -r{toxinidir}/requirements/default.txt
       -r{toxinidir}/requirements/py26.txt
       -r{toxinidir}/requirements/test.txt
commands = {toxinidir}/contrib/release/removepyc.sh {toxinidir}
           pip -E {envdir} install -r contrib/requirements/py26.txt
           pip -E {envdir} install -r contrib/requirements/test.txt
           nosetests --with-xunit                               \
                     --xunit-file={toxinidir}/nosetests.xml     \
                     --with-coverage3 --cover3-xml              \
                     --cover3-html-dir={toxinidir}/cover        \
                     --cover3-xml-file={toxinidir}/coverage.xml

[testenv:py25]
basepython = python2.5
deps = -r{toxinidir}/requirements/default.txt
       -r{toxinidir}/requirements/py25.txt
       -r{toxinidir}/requirements/test.txt
commands = {toxinidir}/contrib/release/removepyc.sh {toxinidir}
           nosetests --with-xunit                               \
                     --xunit-file={toxinidir}/nosetests.xml     \
                     --with-coverage3 --cover3-xml              \
                     --cover3-html-dir={toxinidir}/cover        \
                     --cover3-xml-file={toxinidir}/coverage.xml

[testenv:pypy]
basepython = pypy
deps = -r{toxinidir}/requirements/default.txt
       -r{toxinidir}/requirements/test-pypy.txt
commands = {toxinidir}/contrib/release/removepyc.sh {toxinidir}
           nosetests --with-xunit                               \
                     --xunit-file={toxinidir}/nosetests.xml     \
                     --with-coverage3 --cover3-xml              \
                     --cover3-html-dir={toxinidir}/cover        \
                     --cover3-xml-file={toxinidir}/coverage.xml
